steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'hhttps://github.com/nedakhodabakhshi/gcp-repo-01.git']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']
