steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', 'https://github.com/nedakhodabakhshi/gcp-repo-01.git']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}', '.']

  - name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}']

  # Kubernetes Deployment
  - name: gcr.io/cloud-builders/kubectl
    args:
      - 'set'
      - 'image'
      - 'deployment/cicd-app-1'
      - 'myimgweb-sha256-1-sha2562-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster1'

substitutions:
  _PROJECT_ID: my-codebuild
  _CINAME: myimgweb-sha256-1-sha2562
  _VERSION: v4.0

options:
  logging: CLOUD_LOGGING_ONLY

